[supabase]
# 1-3에서 복사한 Connection String URI를 붙여넣으세요.
uri = "postgresql://postgres:z1x2c3z1x2!@db.tdkyfrzhrvbssigihdrn.supabase.co:5432/postgres"

# 1-3에서 복사한 API 섹션의 Project URL과 anon key를 붙여넣으세요.
url = "https://tdkyfrzhrvbssigihdrn.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRka3lmcnpocnZic3NpZ2loZHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4OTY0MDQsImV4cCI6MjA4MDQ3MjQwNH0.1ggRsyFFjWaQbdiefVw_T3C9tEKFyDSEqbboswhRgx0" 

# 주의: 위 URL, key, uri 값은 반드시 사용자님의 Supabase 정보로 변경해야 합니다.
# 특히 uri의 'DatabasePassword' 부분은 1-1에서 설정한 비밀번호로 변경해야 합니다.
